### ISSUE TITLE
Plugin submission

### ISSUE THREAD

**Issue by orthagh** [l33one/livechat#1]
Hello, 

i received your submission for this plugins on GLPI plugins catalog.

Before i accept it, could you fix the logo url in your xml, it's currently 404.

Regards.

**Comment by l33one** [comment]
Hello Alexandre,

Ready, now it's Ok!


Cordialmente,

[CRC]
Leewan Meneses | Analista de Sistemas e Infraestrutura
| Vector Contact Center | Tecnologia
| mobile: 85986926773<tel:85986926773>
| email: leewan.meneses@outlook.com<mailto:leewan.alves@outlook.com>
| skype: leewan.meneses
Follow us:
[https://img.mysignature.io/s/v3/2/3/7/23772805-4d08-588f-b2c2-f8913127167b.png]<https://chat.whatsapp.com/8586926773>  [https://img.mysignature.io/s/v3/c/8/2/c82fa682-076c-54e3-a38c-8498149e5342.png] <https://www.linkedin.com/in/leewanmeneses/>   [https://img.mysignature.io/s/v3/b/7/b/b7bc4b56-1967-5cef-9458-c0e2bb1f71e3.png] <https://github.com/l33one>    [https://img.mysignature.io/s/v3/d/5/c/d5c659d5-d4fc-5fcc-bf83-180684ff4059.png] <https://www.skype.com/leewan.meneses>         [https://img.mysignature.io/s/v3/9/a/5/9a55e581-d4db-5f76-a42d-75a95ae9d6f1.png] <https://play.google.com/store/apps/developer?id=Leewan+Meneses>       [https://img.mysignature.io/s/v3/6/b/e/6be97932-751b-53bd-93b5-5ea946d4d37e.png] <https://web.telegram.org/leewanmeneses>
IMPORTANT: The contents of this email and any attachments are confidential. It is strictly forbidden to share any part of this message with any third party, without a written consent of the sender. If you received this message by mistake, please reply to this message and follow with its deletion, so that we can ensure such a mistake does not occur in the future.


________________________________
De: Alexandre Delaunay <notifications@github.com>
Enviado: quinta-feira, 30 de abril de 2020 06:35
Para: l33one/livechat <livechat@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: [l33one/livechat] Plugin submission (#1)


Hello,

i received your submission for this plugins on GLPI plugins catalog.

Before i accept it, could you fix the logo url in your xml, it's currently 404.

Regards.

**Comment by orthagh** [comment]
Ok, plugin accepted, the file should be libe in catalog in few minutes.

Regards
